apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3
spec:
  selector:
    matchLabels:
      app: nginx-3
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-3
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docherhub-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-3
  labels:
    app: nginx-3
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-3
  type: LoadBalancer
